vagrant:
  ip: '192.168.22.5'
  hostname: 'example.dev'

ssh_users:
  - ssh_user_name: 'deploy'
    ssh_user_pass: 'no' #put 'no' to lock user
    ssh_user_can_sudo: true
  - ssh_user_name: 'dvadmin'
    ssh_user_pass: 'dvadmin1234'
    ssh_user_can_sudo: true
  - ssh_user_name: 'dev'
    ssh_user_pass: 'dev1234'
    ssh_user_can_sudo: false

mysql_install:
  host: 'localhost'
  root_pass: 'root'

mysql_databases:
  - db_name: 'example_db'
    db_user: 'example_user'
    db_pass: 'example_pass'
    
apache_modules:
  - 'alias'
  - 'proxy'
  - 'proxy_connect'
  - 'proxy_ftp'
  - 'proxy_http'
  - 'proxy_fcgi'
  - 'proxy_scgi'
  - 'proxy_wstunnel'
  - 'proxy_ajp'
  - 'proxy_balancer'
  - 'proxy_express'
  - 'rewrite'
  - 'vhost_alias'
    
sites:
  - site_name: 'VagrantEasy-LAMP-example-app'
    local_path: '../VagrantEasy-LAMP-example-app' # Relative to Vagrantfile location
    remote_path: '/var/www/VagrantEasy-LAMP-example-app'
    enabled: true
    log_level: 'debug'
    host: 'example.dev'
    aliases:
      - 'www.example.dev'
      - 'ww2.example.dev'
    